# Generated by Django 4.0.2 on 2022-02-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
