# Generated by Django 4.0.2 on 2022-02-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='address',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
